### PR TITLE
Update tabs.mdx

### PR DESCRIPTION
**Pull request by diegohaz**
Small fix on docs :)

### CODE REVIEW

**Comment by jameslnewell** [comment]
🙈oops! thanks mate! everything is pretty rough atm, so feel free to change :allthethings:, work reakit in or whatever!

**Comment by jameslnewell** [comment]
Do you know of any automated ways of making sure the code blocks/examples in markdown (like above) actually work?

**Comment by diegohaz** [comment]
> Do you know of any automated ways of making sure the code blocks/examples in markdown (like above) actually work?
I don't! :(
I'm also having this issue here: https://deploy-preview-402--reakit.netlify.com/docs/button/
All the checks are passing, although the code examples are broken.

**Comment by diegohaz** [comment]
But I think for this particular case a linter can help: https://github.com/reakit/reakit/blob/11b7bfa6895818cc7de7bf04d4fca4447965081b/.eslintrc.js#L65-L71

**Comment by jameslnewell** [comment]
oh nice!

**Pull request merged**
